CONNECT JEREMYBUTT/system@10.0.0.69:1521/XEPDB1;

-- Use an anonymous PL/SQL script to
-- drop all tables and sequences in the current schema and
-- suppress any error messages that may displayed 
-- if these objects don't exist

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE DIM_GAME_TYPE PURGE';
	EXECUTE IMMEDIATE 'DROP TABLE DIM_PLAYER PURGE';
	EXECUTE IMMEDIATE 'DROP TABLE DIM_SEASON PURGE';
	EXECUTE IMMEDIATE 'DROP TABLE DIM_TEAM PURGE';
	EXECUTE IMMEDIATE 'DROP TABLE DIM_VENUE PURGE';
	EXECUTE IMMEDIATE 'DROP TABLE FACT_GOALIE PURGE';
	EXECUTE IMMEDIATE 'DROP TABLE FACT_PLAYER PURGE';
	EXECUTE IMMEDIATE 'DROP TABLE FACT_SCHEDULE PURGE';
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('');
END;
/

CREATE TABLE "DIM_GAME_TYPE"
(
    "GAME_TYPE_ID" VARCHAR2(26 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(256 BYTE), 
	"POSTSEASON" VARCHAR2(128 BYTE), 
	 CONSTRAINT "GAME_TYPE_PK" PRIMARY KEY ("GAME_TYPE_ID")
)
;

CREATE TABLE "DIM_PLAYER" 
(	
    "PLAYER_ID" VARCHAR2(7 BYTE) NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(56 BYTE),
	"API_LINK" VARCHAR2(26 BYTE),
	"FIRST_NAME" VARCHAR2(26 BYTE), 
	"LAST_NAME" VARCHAR2(26 BYTE), 
	"PRIMARY_NUMBER" VARCHAR2(2 BYTE), 
	"BIRTH_DATE" DATE, 
	"BIRTH_CITY" VARCHAR2(56 BYTE), 
	"BIRTH_STATE_PROVINCE" VARCHAR2(5 BYTE), 
	"BIRTH_COUNTRY" VARCHAR2(3 BYTE), 
	"NATIONALITY" VARCHAR2(3 BYTE), 
	"HEIGHT" VARCHAR2(6 BYTE), 
	"WEIGHT" NUMBER(3,0), 
	"ACTIVE" VARCHAR2(26 BYTE), 
	"ROOKIE" VARCHAR2(26 BYTE), 
	"SHOOTS" VARCHAR2(2 BYTE), 
	"ROSTER_STATUS" VARCHAR2(1 BYTE), 
	"PRIMARY_POSITION_CODE" VARCHAR2(1 BYTE), 
	"PRIMARY_POSITION_NAME" VARCHAR2(26 BYTE), 
	"PRIMARY_POSITION_TYPE" VARCHAR2(26 BYTE), 
	"PRIMARY_POSITION_ABBREVIATION" VARCHAR2(2 BYTE), 
	"URL" VARCHAR2(128 BYTE),
	"COPYRIGHT" VARCHAR2(256),
	"CURRENT_AGE" NUMBER(2,0), 
	"ALTERNATE_CAPTAIN" VARCHAR2(26 BYTE), 
	"CAPTAIN" VARCHAR2(26 BYTE), 
	"CURRENT_TEAM_ID" VARCHAR2(2 BYTE), 
	"CURRENT_TEAM_NAME" VARCHAR2(26 BYTE),
	"CURRENT_TEAM_LINK" VARCHAR2(56 BYTE),
	 CONSTRAINT "PLAYER_PK" PRIMARY KEY ("PLAYER_ID")
)
;

CREATE TABLE "DIM_SEASON" 
(	
    "SEASON_ID" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"REGULAR_SEASON_START_DATE" DATE, 
	"REGULAR_SEASON_END_DATE" DATE, 
	"SEASON_END_DATE" DATE, 
	"NUMBER_OF_GAMES" NUMBER(38,0), 
	"TIES_IN_USE" VARCHAR2(26 BYTE), 
	"OLYMPICS_PARTICIPATION" VARCHAR2(26 BYTE), 
	"CONFERENCES_IN_USE" VARCHAR2(26 BYTE), 
	"DIVISIONS_IN_USE" VARCHAR2(26 BYTE), 
	"WILD_CARD_IN_USE" VARCHAR2(26 BYTE),
	"URL" VARCHAR2(128),
	"COPYRIGHT" VARCHAR2(256),
	 CONSTRAINT "SEASON_PK" PRIMARY KEY ("SEASON_ID")
);

CREATE TABLE "DIM_TEAM" 
(	
    "TEAM_ID" VARCHAR2(2 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(56 BYTE), 
	"API_LINK" VARCHAR2(26 BYTE),
	"ABBREVIATION" VARCHAR2(3 BYTE), 
	"TEAM_NAME" VARCHAR2(26 BYTE), 
	"LOCATION_NAME" VARCHAR2(26 BYTE), 
	"FIRST_YEAR_OF_PLAY" NUMBER(4,0), 
	"SHORT_NAME" VARCHAR2(26 BYTE), 
	"OFFICIAL_SITE_URL" VARCHAR2(128 BYTE), 
	"FRANCHISE_ID" VARCHAR2(2 BYTE), 
	"ACTIVE" VARCHAR2(26 BYTE), 
	"VENUE_NAME" VARCHAR2(26 BYTE), 
	"VENUE_LINK" VARCHAR2(26),
	"VENUE_CITY" VARCHAR2(26 BYTE), 
	"VENUE_ID" NUMBER(4,0), 
	"VENUE_TIME_ZONE_ID" VARCHAR2(26 BYTE), 
	"VENUE_TIME_ZONE_OFFSET" NUMBER(38,0), 
	"VENUE_TIME_ZONE_TZ" VARCHAR2(26 BYTE), 
	"DIVISION_ID" VARCHAR2(2 BYTE), 
	"DIVISION_NAME" VARCHAR2(26 BYTE), 
	"DIVISION_NAME_SHORT" VARCHAR2(5 BYTE), 
	"DIVISION_LINK" VARCHAR2(26),
	"DIVISION_ABBREVIATION" VARCHAR2(1 BYTE), 
	"CONFERENCE_ID" VARCHAR2(2 BYTE), 
	"CONFERENCE_NAME" VARCHAR2(26 BYTE),
	"CONFERENCE_LINK" VARCHAR2(26),
	"FRANCHISE_FRANCHISE_ID" VARCHAR2(2 BYTE), 
	"FRANCHISE_TEAM_NAME" VARCHAR2(26 BYTE), 
	"FRANCHISE_LINK" VARCHAR2(26),
	"URL" VARCHAR2(128 BYTE),
	"COPYRIGHT" VARCHAR2(256 BYTE),
	 CONSTRAINT "TEAM_PK" PRIMARY KEY ("TEAM_ID")
)
;

CREATE TABLE "DIM_VENUE" 
(	
    "VENUE_ID" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"VENUE_NAME" VARCHAR2(128 BYTE), 
	"VENUE_LINK" VARCHAR2(26 BYTE),
	"APP_ENABLED" VARCHAR2(26 BYTE),
	"URL" VARCHAR2(128 BYTE),
	"COPYRIGHT" VARCHAR2(256 BYTE),
	 CONSTRAINT "VENUE_PK" PRIMARY KEY ("VENUE_ID")
)
;

CREATE TABLE "FACT_GOALIE" 
   (
    "GAME_ID"                               VARCHAR2(10 BYTE)   NOT NULL ENABLE, 
	"PLAYER_ID"                             VARCHAR2(7 BYTE)    NOT NULL ENABLE, 
	"PLAYER_NAME"                           VARCHAR2(128 BYTE), 
	"PRIMARY_POSITION_CODE"                 VARCHAR2(1 BYTE), 
	"TEAM_ID"                               VARCHAR2(2 BYTE), 
	"TIME_ON_ICE"                           VARCHAR2(6 BYTE), 
	"ASSISTS"                               NUMBER(2,0), 
	"GOALS"                                 NUMBER(2,0), 
	"PENALTY_MINUTES"                                   NUMBER(3,0), 
	"SHOTS"                                 NUMBER(2,0), 
	"SAVES"                                 NUMBER(3,0), 
	"POWER_PLAY_SAVES"                      NUMBER(3,0), 
	"SHORT_HANDED_SAVES"                    NUMBER(3,0), 
	"EVEN_SAVES"                            NUMBER(3,0), 
	"SHORT_HANDED_SHOTS_AGAINST"            NUMBER(3,0), 
	"EVEN_SHOTS_AGAINST"                    NUMBER(3,0), 
	"POWER_PLAY_SHOTS_AGAINST"              NUMBER(3,0), 
	"DECISION"                              VARCHAR2(5 BYTE), 
	"SAVE_PERCENTAGE"                       NUMBER(5,2), 
	"EVEN_STRENGTH_SAVE_PERCENTAGE"         NUMBER(5,2),
	CONSTRAINT "FACT_GOALIE_PK"
		PRIMARY KEY ("GAME_ID", "PLAYER_ID"),
	CONSTRAINT "FACT_GOALIE_FK_PLAYER" FOREIGN KEY ("PLAYER_ID")
		REFERENCES "DIM_PLAYER" ("PLAYER_ID")
   )
;

CREATE TABLE "FACT_PLAYER" 
(	
	"GAME_ID" VARCHAR2(10 BYTE)						NOT NULL ENABLE, 
	"PLAYER_ID" VARCHAR2(7 BYTE)					NOT NULL ENABLE, 
	"PLAYER_NAME" VARCHAR2(128 BYTE), 
	"PRIMARY_POSITION_CODE" VARCHAR2(1 BYTE), 
	"TEAM_ID" VARCHAR2(2 BYTE), 
	"TIME_ON_ICE" VARCHAR2(6 BYTE), 
	"ASSISTS" NUMBER(2,0), 
	"GOALS" NUMBER(2,0), 
	"SHOTS" NUMBER(2,0), 
	"HITS" NUMBER(2,0), 
	"POWER_PLAY_GOALS" NUMBER(2,0), 
	"POWER_PLAY_ASSISTS" NUMBER(2,0), 
	"PENALTY_MINUTES" NUMBER(3,0), 
	"FACE_OFF_WINS" NUMBER(2,0), 
	"FACEOFF_TAKEN" NUMBER(2,0), 
	"TAKEAWAYS" NUMBER(2,0), 
	"GIVEAWAYS" NUMBER(2,0), 
	"SHORT_HANDED_GOALS" NUMBER(2,0), 
	"SHORT_HANDED_ASSISTS" NUMBER(2,0), 
	"BLOCKED" NUMBER(2,0), 
	"PLUS_MINUS" NUMBER(2,0), 
	"EVEN_TIME_ON_ICE" VARCHAR2(6 BYTE), 
	"POWER_PLAY_TIME_ON_ICE" VARCHAR2(6 BYTE), 
	"SHORT_HANDED_TIME_ON_ICE" VARCHAR2(6 BYTE), 
	"FACE_OFF_PCT" NUMBER(3,0), 
	 CONSTRAINT "FACT_PLAYER_PK" 
		PRIMARY KEY ("GAME_ID", "PLAYER_ID"),
	 CONSTRAINT "FACT_PLAYER_FK_PLAYER" FOREIGN KEY ("PLAYER_ID")
		REFERENCES "DIM_PLAYER" ("PLAYER_ID")
)
;

CREATE TABLE fact_schedule 
( 
	GAME_DATE DATE,
    TOTAL_ITEMS NUMBER(38),
    TOTAL_EVENTS NUMBER(38),
    TOTAL_GAMES NUMBER(2),
    TOTAL_MATCHES NUMBER(38),
    GAME_PK NUMBER(10),
    API_LINK VARCHAR2(128),
    GAME_TYPE VARCHAR2(26),
    SEASON VARCHAR2(8),
    GAME_DATE_TIME VARCHAR2(20),
    STATUS_ABSTRACT_GAME_STATE VARCHAR2(26),
    STATUS_CODED_GAME_STATE VARCHAR2(38),
    STATUS_DETAILED_STATE VARCHAR2(26),
    STATUS_STATUS_CODE VARCHAR2(38),
    STATUS_START_TIME_TBD VARCHAR2(26),
    TEAMS_AWAY_SCORE NUMBER(2),
    TEAMS_AWAY_LEAGUE_RECORD_WINS NUMBER(2),
    TEAMS_AWAY_LEAGUE_RECORD_LOSSES NUMBER(3),
    TEAMS_AWAY_LEAGUE_RECORD_OT NUMBER(2),
    TEAMS_AWAY_LEAGUE_RECORD_TYPE VARCHAR2(26),
    TEAMS_AWAY_TEAM_ID VARCHAR2(38),
    TEAMS_AWAY_TEAM_NAME VARCHAR2(52),
    TEAMS_AWAY_TEAM_LINK VARCHAR2(52),
    TEAMS_HOME_SCORE NUMBER(2),
    TEAMS_HOME_LEAGUE_RECORD_WINS NUMBER(2),
    TEAMS_HOME_LEAGUE_RECORD_LOSSES NUMBER(2),
    TEAMS_HOME_LEAGUE_RECORD_OT NUMBER(2),
    TEAMS_HOME_LEAGUE_RECORD_TYPE VARCHAR2(26),
    TEAMS_HOME_TEAM_ID VARCHAR2(38),
    TEAMS_HOME_TEAM_NAME VARCHAR2(52),
    TEAMS_HOME_TEAM_LINK VARCHAR2(52),
    VENUE_ID VARCHAR2(38),
    VENUE_NAME VARCHAR2(256),
    VENUE_LINK VARCHAR2(52),
    CONTENT_LINK VARCHAR2(256),
	CONSTRAINT GAME_PK
		PRIMARY KEY (GAME_PK),
	CONSTRAINT FACT_SCHEDULE_FK_SEASON FOREIGN KEY (SEASON)
		REFERENCES DIM_SEASON (SEASON_ID)
);