CREATE TABLE dim_team (
    team_id                     NUMBER(38,0) NOT NULL ENABLE, 
    team_full_name              VARCHAR2(56 BYTE), 
    team_link                   VARCHAR2(56 BYTE), 
    team_abbreviation           VARCHAR2(3 BYTE), 
    team_name                   VARCHAR2(26 BYTE), 
    location_name               VARCHAR2(26 BYTE),
    first_year_of_play          NUMBER(4,0), 
    team_short_name             VARCHAR2(26 BYTE), 
    official_site_url           VARCHAR2(128 BYTE),
    active                      VARCHAR2(26 BYTE), 
    venue_name                  VARCHAR2(26 BYTE), 
    venue_link                  VARCHAR2(56 BYTE), 
    venue_city                  VARCHAR2(26 BYTE),
    venue_time_zone_id          VARCHAR2(32 BYTE), 
    venue_time_zone_offset      NUMBER(38,0), 
    venue_time_zone_tz          VARCHAR2(26 BYTE),
    division_id                 NUMBER(38,0), 
    division_name               VARCHAR2(26 BYTE), 
    division_name_short         VARCHAR2(5 BYTE), 
    division_link               VARCHAR2(56 BYTE),
    division_abbreviation       VARCHAR2(1 BYTE), 
    conference_id               NUMBER(38,0), 
    conference_name             VARCHAR2(26 BYTE),
    conference_link             VARCHAR2(56 BYTE), 
    franchise_id                NUMBER(38,0), 
    franchise_team_name         VARCHAR2(26 BYTE),
    franchise_link              VARCHAR2(56 BYTE), 
    venue_id                    NUMBER(38,0),
    load_date                   DATE,
    CONSTRAINT team_pk PRIMARY KEY (team_id)
)